version: '3'
services:
  gorn-backend:
    container_name: gorn-backend
    build: ./gorn-backend
    ports: 
      - 8080:8080 
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - gorn-postgres          
    networks:
      - fullstack

  gorn-frontend:
    container_name: gorn-frontend
    build: ./gorn-frontend
    ports: 
      - 3000:3000 
    restart: on-failure
    volumes:
      - hosting:/usr/src/app/
    depends_on:
      - gorn-postgres          
    networks:
      - fullstack


  gorn-postgres:
    image: postgres:latest
    container_name: gorn-postgres
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST} 
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - fullstack
    
  gorn-pgadmin:
    image: dpage/pgadmin4
    container_name: gorn-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - gorn-postgres
    ports:
      - "5050:80"
    networks:
      - fullstack
    restart: unless-stopped

volumes:
  api:
  hosting:
  database_postgres:                 

networks:
  fullstack:
    driver: bridge
